### ISSUE TITLE
Modify the page where it asks for additional information.

### ISSUE THREAD

**Issue by himanshuyv** [OSDG-IIITH/CabMiloge#14]
## Description

If the redirection is successful using cookies or CAS, it asks that you please provide additional information. Modify that page and tell them it is public (gender and batch info). Create a 'learn more' button; once you click on 'Learn More', it will just tell you why we collect this data (for the ML model). Have a 'rather not say' option for gender and batch.

## Files

./templates/SignUp.html
./templates/LogIn.html
./app.py
./db.py

## To Reproduce

Just try to login with your IIIT credentials by removing your entry from the database. This can be done by running a query in the file './db.py'.

## Tasks

- [ ] Create 'Learn More' button
- [ ] Modify the options for the Gender and batch
- [ ] Change the database according to the current logic

**Comment by himanshuyv** [comment]
Not required as of now.
