### ISSUE TITLE
Add edit profile page

### ISSUE THREAD

**Issue by himanshuyv** [OSDG-IIITH/CabMiloge#15]
## Description
Add an edit profile option, which should appear when clicking the name, along with a logout option, as shown in the gif below.

## Screenshot

![Screenshot 2024-05-26 113435](https://github.com/OSDG-IIITH/CabMiloge/assets/71442507/49c62546-7890-4766-a5aa-c500e3fb51dc)
![Untitled video - Made with Clipchamp](https://github.com/OSDG-IIITH/CabMiloge/assets/71442507/bdac5799-dc2d-4f68-ad2b-d04d589ec00c)

## Files

./app.py
./templates/index.html

## Tasks

- [ ] Add edit profile option.
- [ ] Create a page with a form to take the latest inputs to update the fields that were asked in the additional information.
- [ ] Add the logic to modify the database.
