### ISSUE TITLE
Improve Signup UX

### ISSUE THREAD

**Issue by StarryBadger** [OSDG-IIITH/CabMiloge#16]
## Description
For a user without a prior CabMiloge account, on successful redirection post CAS login, the message "c" is displayed in red. This reads as an error despite being the intended control flow for signing up, and is thus confusing. The message needs to be removed. 

A 'show more' drop down text [explaining that we collect the batch and gender information to allow users to more informed cabmate choices] needs to be added.

## Screenshots, Videos
![240528_17h26m53s_screenshot](https://github.com/OSDG-IIITH/CabMiloge/assets/127508741/7ab28d4a-9f47-420e-9dc4-6a53be7d467b)

## Files
[SignUp.html](https://github.com/OSDG-IIITH/CabMiloge/blob/main/templates/SignUp.html)

## To Reproduce  
Sign In with an unregistered (on CabMiloge) IIIT email address and go through the CAS registration with successful redirection. 

## Tasks  
- [ ] Remove the error message 'User not found! Please sign up'
- [ ] Fix CSS: The top of the extra information form is obscured by the header and the bottom has extra space.  (refer to screenshot)
- [ ] Add drop down additional text about why the information (gender, batch) is required
- [ ] Add a 'Prefer not to say' option for the Gender (and Batch?)
