### ISSUE TITLE
Separate  "Add New" page for Upcoming Travel

### ISSUE THREAD

**Issue by StarryBadger** [OSDG-IIITH/CabMiloge#18]
## Description
Make "Add New" a separate page for adding new and upcoming travel plans. This provides separation of concerns disconnecting the Upcoming Travels and Add New Page from being accessible from the other through scrolling. Improve the UI of the form for this page.

## Files
./app.py
./templates/index.html

## Tasks

- [ ] Separate page for 'Add New'
- [ ] Navigation Bar Indication for current page (Add New/Upcoming Travels)
- [ ] Improve UI for 'Add New' page form. [Currently is default HTML form elements]
- [ ]  Change Form Submit Button to match remaining website aesthetics.
